version: '3.7'

networks:
  selenoid:
    external:
      name: selenoid

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - selenoid
    ports:
      - 4444:4444
    volumes:
      - ./selenoid/config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/config/video:/opt/selenoid/video
      - ./selenoid/config/logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./selenoid/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]

  selenoid-ui:
    image: aerokube/selenoid-ui
    networks:
      - selenoid
    depends_on:
      - selenoid
    ports:
      - 8080:8080
    command: ["--selenoid-uri", "http://selenoid:4444"]
